export const cmsPre = {
  cms: [
    {
      id: 10,
      image:
        "http://192.168.30.12:8000/media/profile/Pexels_Photo_3835638.jpeg",
      link: "null",
      text: '{"subheading":"Wedding Ceremony","heading":"Kabin & Udita"}',
      holder: "celebrations-hero-showcase-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 11,
      image:
        "http://192.168.30.12:8000/media/profile/Wedding_Venue_White_Flowers.jpeg",
      link: "null",
      text: '{"subheading":"Wedding Ceremony","heading":"Saurav & Suhana"}',
      holder: "celebrations-hero-showcase-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 12,
      image:
        "http://192.168.30.12:8000/media/profile/Family_Christmas_Dinner_7P7L4hP.webp",
      link: "null",
      text: '{"subheading":"Seasonal Party","heading":"Christmas Celebration"}',
      holder: "celebrations-hero-showcase-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 13,
      image: null,
      link: null,
      text: null,
      holder: "celebrations-hero-showcase-4",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 14,
      image: null,
      link: "null",
      text: '{"subheading":"The Classics Celebrations","heading1":"We are storytelling","heading2":"experts, and our","heading3":"events tell their own","heading4":"story","tagline":"Here for your cherished moments"}',
      holder: "celebrations-hero-content",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 15,
      image: null,
      link: null,
      text: '{"subheading":"Here for your cherished moments","heading1":"From Dreamy Beginnings to Joyful","heading2":"Endings - We perfect every moment","heading3":"before, during & after."}',
      holder: "celebrations-home-intro-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 16,
      image: "http://192.168.30.12:8000/media/profile/pre-planning.jpg",
      link: "null",
      text: '{"quote1":"Preparations Pre-Event","quote2":"The work behind the scenes","quote3":"The prep before the party","quote4":"The magic behind the scenes","tagline_main":"METHODS","detailed_tagline":"Visualising the event","detailed_quote":"Visualising the perfect event","detailed_services":"Venue Selection - Theme Selection - Requirement Analysis - Event Planning - Decor Selection - Activity Planning"}',
      holder: "celebrations-home-phase-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 17,
      image: "http://192.168.30.12:8000/media/profile/Pin_page_image.jpg",
      link: "null",
      text: '{"quote1":"Work During Event","quote2":"The Work on the scene","quote3":"Work behind the event","quote4":"Magic During the Show","tagline_main":"organising the event","detailed_tagline":"Hosting the event","detailed_quote":"organising the event","detailed_services":"Venue Selection - Theme Selection - Requirement Analysis - Event Planning - Decor Selection - Activity Planning"}',
      holder: "celebrations-home-phase-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 18,
      image:
        "http://192.168.30.12:8000/media/profile/Single_Line_Gift_Design.jpg",
      link: "null",
      text: '{"quote1":"PREPARATION PRE EVENT","quote2":"PREPARATION PRE EVENT","quote3":"PREPARATION PRE EVENT","quote4":"PREPARATION PRE EVENT","tagline_main":"EFFECTS","detailed_tagline":"After the Event","detailed_quote":"After the event","detailed_services":"Venue Selection - Theme Selection - Requirement Analysis - Event Planning - Decor Selection - Activity Planning"}',
      holder: "celebrations-home-phase-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 19,
      image: null,
      link: null,
      text: null,
      holder: "celebrations-home-end-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 20,
      image: null,
      link: null,
      text: null,
      holder: "celebrations-home-end-instagram-1",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 21,
      image: null,
      link: null,
      text: null,
      holder: "celebrations-home-end-instagram-2",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 22,
      image: null,
      link: null,
      text: null,
      holder: "celebrations-home-end-instagram-3",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 23,
      image: "http://192.168.30.12:8000/media/profile/Image_3840x2560.webp",
      link: "null",
      text: '{"subheading":"ABOUT","heading1":"A team of experts,","heading2":"radically transforming","heading3":"events & event planning","paragraph1":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements.","paragraph2":"Isabl technology unlocks the full potential of genomic medicine – contributing to the advancement of research aiming to provide better outcomes for every patient."}',
      holder: "celebrations-about-intro",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 24,
      image: null,
      link: null,
      text: '{"subheading":"Behind The Name","heading1":"Turning every event into a meaningful","heading2":"experience, from passion to perfection, the origin of","heading3":"the Classics Celebrations","paragraph1":"Once upon a time, twenty-one years or so ago, two lifelines crossed and an epic restaurant server-crush was born. When we met in 2001, there was an instant understanding that our connection was meant for something big. We just didn’t know what it was yet.","paragraph2":"Luxe was born on the foundation that everything happens for a reason. The Luxe family of brands was created in June of \'09 out of a passion for hospitality, leadership and entrepreneurship."}',
      holder: "celebrations-about-history-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 25,
      image:
        "http://192.168.30.12:8000/media/profile/Family_Christmas_Dinner_8Cua0gb.webp",
      link: "null",
      text: "{}",
      holder: "celebrations-about-history-image-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "t1",
      meta_description: "t2",
    },
    {
      id: 26,
      image: "http://192.168.30.12:8000/media/profile/Pin_Image.jpg",
      link: "null",
      text: "{}",
      holder: "celebrations-about-history-image-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 27,
      image:
        "http://192.168.30.12:8000/media/profile/WhatsApp_Image_2024-12-08_at_07.56.39.jpeg",
      link: "null",
      text: "{}",
      holder: "celebrations-about-history-image-4",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 28,
      image: null,
      link: null,
      text: '{"subheading":"We L.E.A.D - Listen, Execute, Anticipate & Deliver","heading1":"Mastering Storytelling","heading2":"Our Events,","heading3":"Speak for themselves","paragraph1":"WE L.E.A.D. - LISTEN, EXECUTE, ANTICIPATE & DELIVER. It\'s a system we own and take pride in, and it ensures every wedding we design or produce will be an authentic success.","paragraph2":"We work this way because we expect the same from ourselves and every partner we work with."}',
      holder: "celebrations-about-execution-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 29,
      image: null,
      link: null,
      text: '{"subheading":"Phases of Event Operation","heading1":"How we make,","heading2":"your events happen","heading3":"the right way.","paragraph1":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements."}',
      holder: "celebrations-about-phase-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 30,
      image: null,
      link: "null",
      text: '{"description":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements."}',
      holder: "celebrations-about-phase-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 31,
      image: null,
      link: "null",
      text: '{"description":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements."}',
      holder: "celebrations-about-phase-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 32,
      image: null,
      link: "null",
      text: '{"description":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements."}',
      holder: "celebrations-about-phase-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 33,
      image:
        "http://192.168.30.12:8000/media/profile/Image_3840x2560_xWDs4DE.webp",
      link: "null",
      text: '{"subheading":"Classics Events","heading1":"A team of experts,","heading2":"radically transforming","heading3":"events & event planning","paragraph1":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements.","paragraph2":"Isabl technology unlocks the full potential of genomic medicine – contributing to the advancement of research aiming to provide better outcomes for every patient."}',
      holder: "events-about-intro",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 34,
      image: null,
      link: null,
      text: null,
      holder: "events-about-history-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 35,
      image: null,
      link: null,
      text: null,
      holder: "events-about-image-1",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 36,
      image: null,
      link: null,
      text: null,
      holder: "events-about-image-2",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 37,
      image: null,
      link: null,
      text: null,
      holder: "events-about-image-3",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 38,
      image: null,
      link: null,
      text: '{"subheading":"WE L.E.A.D - Listen, Execute, Anticipate & Devlier","heading1":"Mastering Storytelling","heading2":"our events,","heading3":"speak for themselves","paragraph1":"WE L.E.A.D. - LISTEN, EXECUTE, ANTICIPATE & DELIVER. It\'s a system we own and take pride in, and it ensures every wedding we design or produce will be an authentic success.","paragraph2":"We work this way because we expect the same from ourselves and every partner we work with."}',
      holder: "events-about-execution",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 39,
      image: null,
      link: null,
      text: null,
      holder: "events-about-phase-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 40,
      image: null,
      link: null,
      text: null,
      holder: "events-about-phase-1",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 41,
      image: null,
      link: "null",
      text: '{"description":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements."}',
      holder: "events-about-phase-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 42,
      image: null,
      link: "null",
      text: '{"description":"Targeted sequencing – a significant step in tailored cancer care. But, only a select population have benefited from these advancements."}',
      holder: "events-about-phase-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 43,
      image: null,
      link: null,
      text: '{"subheading":"The Classics Events","heading1":"We are storytelling","heading2":"exports, and our","heading3":"events tell their own","heading4":"story","tagline":"Here for your corporate gatherings."}',
      holder: "event-home-hero-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 44,
      image:
        "http://192.168.30.12:8000/media/profile/Image_3840x2560_EktL12p.webp",
      link: "null",
      text: '{"subheading":"HACKATHON","heading":"Everest Hackathon"}',
      holder: "event-home-hero-showcase-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 45,
      image: null,
      link: null,
      text: null,
      holder: "event-home-hero-showcase-2",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 46,
      image: null,
      link: null,
      text: null,
      holder: "event-home-hero-showcase-3",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 47,
      image: null,
      link: null,
      text: null,
      holder: "event-home-hero-showcase-4",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 48,
      image: "http://192.168.30.12:8000/media/profile/Google_Logo_2015.webp",
      link: "null",
      text: "{}",
      holder: "events-home-brand-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 49,
      image:
        "http://192.168.30.12:8000/media/profile/Google_Logo_2015_SzjABop.webp",
      link: "null",
      text: "{}",
      holder: "events-home-brand-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 50,
      image:
        "http://192.168.30.12:8000/media/profile/Google_Logo_2015_ve9xyME.webp",
      link: "null",
      text: "{}",
      holder: "events-home-brand-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 51,
      image:
        "http://192.168.30.12:8000/media/profile/Google_Logo_2015_LaJ8KEa.webp",
      link: "null",
      text: "{}",
      holder: "events-home-brand-4",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 52,
      image:
        "http://192.168.30.12:8000/media/profile/Google_Logo_2015_7hOjXwu.webp",
      link: "null",
      text: "{}",
      holder: "events-home-brand-5",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 53,
      image:
        "http://192.168.30.12:8000/media/profile/Google_Logo_2015_3JhEuix.webp",
      link: "null",
      text: "{}",
      holder: "events-home-brand-6",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 54,
      image: null,
      link: null,
      text: '{"subheading":"Chip Health","heading1":"The \'Ocasionally remarkable,","heading2":"moments\' shouldn\'t be left to","heading3":"chance! they should be","heading4":"planned for, invested in","post1":"Thrive Foundation for Youth Professor of Organizational","post2":"Behavior at the Standford Graduate School of Business"}',
      holder: "events-hero-intro-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 55,
      image: null,
      link: null,
      text: '{"subheading":"Meeting not the hosting","heading1":"Focus on your","heading2":"meeting, not the","heading4":"hosting - let us.","paragraph":"this is a paragraph"}',
      holder: "event-home-showcase-s1-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 56,
      image:
        "http://192.168.30.12:8000/media/profile/Image_3840x2560_HYD6kHm.webp",
      link: "null",
      text: "{}",
      holder: "event-home-showcase-s1-image-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 57,
      image: "http://192.168.30.12:8000/media/profile/pre-planning_aBoTuA6.jpg",
      link: "null",
      text: "{}",
      holder: "event-home-showcase-s1-image-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 58,
      image: "http://192.168.30.12:8000/media/profile/pre-planning_tocTWdI.jpg",
      link: "null",
      text: "{}",
      holder: "event-home-showcase-s1-image-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 59,
      image: null,
      link: null,
      text: '{"subheading":"Galas & Events","heading1":"Elevate your Experience:","heading2":"Where Unforgettable Moments","heading4":"Begin,","paragraph":"this is a paragraph"}',
      holder: "event-home-showcase-s2-content",
      is_active: false,
      caption: null,
      attribute: null,
      meta_keyphrase: null,
      meta_description: null,
    },
    {
      id: 60,
      image: "http://192.168.30.12:8000/media/profile/pre-planning_zh9Lgv8.jpg",
      link: "null",
      text: "{}",
      holder: "event-home-showcase-s2-image-1",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 61,
      image: "http://192.168.30.12:8000/media/profile/images_y9xZ6gN.png",
      link: "null",
      text: "{}",
      holder: "event-home-showcase-s2-image-2",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
    {
      id: 62,
      image: "http://192.168.30.12:8000/media/profile/40_URY75KL.png",
      link: "null",
      text: "{}",
      holder: "event-home-showcase-s2-image-3",
      is_active: false,
      caption: "null",
      attribute: "null",
      meta_keyphrase: "null",
      meta_description: "null",
    },
  ],
  testimonials: [
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Alex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Palex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Walex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Dalex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Ralex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Balex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Talex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Alex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Alex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
    {
      image:
        "https://www.freepnglogos.com/uploads/google-logo-new-history-png-9.png",
      signature_image:
        "https://www.pngall.com/wp-content/uploads/14/Signature-PNG-Photos.png",
      name: "Xalex Wang",
      company: "Mo Media",
      post: "Managing Director",
      message:
        "The “occasionally remarkable” moments shouldn’t be left to chance! They should be planned for, invested in.",
    },
  ],
  events: [
    {
      id: 1,
      event_images: [
        {
          id: 2,
          image: "http://192.168.30.12:8000/media/events/b00e2752cf1a4d61.png",
          meta_keyphrase: "null",
          meta_description: "null",
          holder: "5",
          is_active: false,
          caption: "testee",
          event: 1,
        },
        {
          id: 3,
          image: "http://192.168.30.12:8000/media/events/226f356029b94917.png",
          meta_keyphrase: "null",
          meta_description: "null",
          holder: "5",
          is_active: false,
          caption: "testee",
          event: 1,
        },
      ],
      event_video: [
        {
          id: 1,
          link: "https://www.youtube.com/embed/mzJ4vCjSt28",
          holder: "2",
          is_active: false,
          caption: "testee",
          event: 1,
        },
      ],
      shortname: "Raman & Eve",
      fullname: "Cowwby wedding at rama",
      meta_keyphrase: null,
      meta_description: null,
      event_date: "2024-12-06",
      venue: "ASD",
      theme: "Floran Nightsky",
      highlight_message: "asdas",
      event_description: "asdfasdf",
      is_featured: false,
      color: null,
      event_category: 1,
      company: 2,
    },
    {
      id: 2,
      event_images: [],
      event_video: [],
      shortname: "test",
      fullname: "test",
      meta_keyphrase: null,
      meta_description: null,
      event_date: "2025-01-02",
      venue: "test",
      theme: "test",
      highlight_message: "test",
      event_description: "test",
      is_featured: false,
      color: null,
      event_category: 1,
      company: 1,
    },
    {
      id: 3,
      event_images: [],
      event_video: [],
      shortname: "test2",
      fullname: "testtes",
      meta_keyphrase: null,
      meta_description: null,
      event_date: "2024-12-26",
      venue: "test",
      theme: "test",
      highlight_message: "test",
      event_description: "test",
      is_featured: false,
      color: null,
      event_category: 1,
      company: 1,
    },
    {
      id: 4,
      event_images: [],
      event_video: [],
      shortname: "Kabin & Udita",
      fullname: "Wedding Ceremony in Nepal,",
      meta_keyphrase: null,
      meta_description: null,
      event_date: "2024-12-27",
      venue: "XY Banquet",
      theme: "Floral Nightsky",
      highlight_message: "Till death do us part",
      event_description: "Hello darkness my old friend",
      is_featured: false,
      color: null,
      event_category: 1,
      company: 1,
    },
    {
      id: 5,
      event_images: [
        {
          id: 4,
          image: "http://192.168.30.12:8000/media/events/eb8a74fc9920473.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "1",
          is_active: false,
          caption: "The smiles",
          event: 5,
        },
        {
          id: 5,
          image: "http://192.168.30.12:8000/media/events/98bf94980e33413.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "2",
          is_active: false,
          caption: "Drive to the venue",
          event: 5,
        },
        {
          id: 6,
          image: "http://192.168.30.12:8000/media/events/de2b878715ec47b.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "3",
          is_active: false,
          caption: "the good times",
          event: 5,
        },
        {
          id: 7,
          image: "http://192.168.30.12:8000/media/events/6559ca0c454d4cb.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "4",
          is_active: false,
          caption: "drive by",
          event: 5,
        },
        {
          id: 8,
          image: "http://192.168.30.12:8000/media/events/77f3db2b9a3f413.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "5",
          is_active: false,
          caption: "Flowers",
          event: 5,
        },
        {
          id: 9,
          image: "http://192.168.30.12:8000/media/events/b64ff3b1cf4c4cd.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "6",
          is_active: false,
          caption: "the gang",
          event: 5,
        },
        {
          id: 10,
          image: "http://192.168.30.12:8000/media/events/03ce392bf37647b.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "7",
          is_active: false,
          caption: "camera moment",
          event: 5,
        },
        {
          id: 11,
          image: "http://192.168.30.12:8000/media/events/ecb4f2b2840d444.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "8",
          is_active: false,
          caption: "the ride",
          event: 5,
        },
        {
          id: 12,
          image: "http://192.168.30.12:8000/media/events/5e357ac89424486.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "9",
          is_active: false,
          caption: "dance under the sun",
          event: 5,
        },
        {
          id: 13,
          image: "http://192.168.30.12:8000/media/events/b0d297932dc14dc.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "10",
          is_active: false,
          caption: "beauty",
          event: 5,
        },
        {
          id: 14,
          image: "http://192.168.30.12:8000/media/events/bf97d52b338d4d9.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "11",
          is_active: false,
          caption: "and the beast",
          event: 5,
        },
        {
          id: 15,
          image: "http://192.168.30.12:8000/media/events/b18e0a16596340c.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "12",
          is_active: false,
          caption: "kiss",
          event: 5,
        },
        {
          id: 16,
          image: "http://192.168.30.12:8000/media/events/80aabc899c094cb.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "13",
          is_active: false,
          caption: "the gang",
          event: 5,
        },
        {
          id: 17,
          image: "http://192.168.30.12:8000/media/events/24d52619fbd5414.webp",
          meta_keyphrase: null,
          meta_description: null,
          holder: "14",
          is_active: false,
          caption: "x",
          event: 5,
        },
      ],
      event_video: [],
      shortname: "Lucie & Paul",
      fullname: "Beautiful beach side weeding event for Lucie.& Paul",
      meta_keyphrase: null,
      meta_description: null,
      event_date: "2024-12-27",
      venue: "Robin Beach, USA",
      theme: "Beach Wedding",
      highlight_message: "Till death do us part.",
      event_description:
        "A stunning beachside wedding celebration for Lucie & Paul, filled with love, laughter, and breathtaking views.",
      is_featured: false,
      color: null,
      event_category: 1,
      company: 1,
    },
  ],
};
